version: '3.8'

x-common-variables: &common-variables
  MYSQL_DATABASE: song_list
  MYSQL_USER: MYSQL_USER
  MYSQL_PASSWORD: MYSQL_ROOT_PASSWORD

services:
  mysql_db:
    image: mysql
    restart: always
    cap_add:
      - SYS_NICE
    volumes:
      - "./setup.sql:/docker-entrypoint-initdb.d/setup.sql"
    ports:
      - "9906:3306"
    environment:
      <<: *common-variables
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_HOST: localhost

  server:
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: "./server"
    depends_on:
      - mysql_db
      - client
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql_db
    ports:
      - "4000:4000"

  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app

  adminer:
      image: adminer:latest
      restart: unless-stopped
      ports:
        - 8000:8080
      depends_on:
        - mysql_db
      environment:
        ADMINER_DEFAULT_SERVER: mysql_db