CREATE TABLE song_list (
    id int(11) NOT NULL AUTO_INCREMENT,
    song_name varchar(50) NOT NULL,
    band varchar(50) NOT NULL,
    year varchar(50) NOT NULL, 
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8;